[package]
name = "supabase-rust"
version = "0.1.0"
edition = "2021"
authors = ["Supabase Rust Client Contributors"]
description = "Rust client for Supabase"
license = "MIT"
repository = "https://github.com/supabase/supabase-rust"
documentation = "https://docs.rs/supabase-rust"
keywords = ["supabase", "postgres", "database", "api", "client"]
categories = ["database", "api-bindings", "web-programming"]
readme = "README.md"

[workspace]
members = [
    ".",
    "crates/auth",
    "crates/postgrest",
    "crates/storage",
    "crates/realtime",
    "crates/functions",
    "examples"
]

[dependencies]
# HTTP クライアント
reqwest = { version = "0.11", features = ["json", "multipart"] }
# 非同期ランタイム
tokio = { version = "1.0", features = ["full"] }
# シリアライズ/デシリアライズ
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# エラーハンドリング
thiserror = "1.0"
anyhow = "1.0"
# URL 操作
url = "2.3"
# エンコーディング
base64 = "0.21"
# 非同期トレイト
async-trait = "0.1"
# JWT 操作
jsonwebtoken = "9.1"
# ログ
log = "0.4"
# WebSocket (for Realtime)
tokio-tungstenite = { version = "0.20", features = ["native-tls"] }
# HTTP ヘッダー
http = "0.2"
# UUID 生成
uuid = { version = "1.4", features = ["v4", "serde"] }
# 環境変数
dotenv = "0.15"
# 時間
chrono = { version = "0.4", features = ["serde"] }

# サブクレート依存関係
supabase-auth = { path = "crates/auth", version = "0.1.0" }
supabase-postgrest = { path = "crates/postgrest", version = "0.1.0" }
supabase-storage = { path = "crates/storage", version = "0.1.0" }
supabase-realtime = { path = "crates/realtime", version = "0.1.0" }
supabase-functions = { path = "crates/functions", version = "0.1.0" }

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.0"
wiremock = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = "1.18"