[package]
name = "supabase-rust-gftd"
version = "0.1.0"
edition = "2021"
authors = ["Jun Kawasaki"]
description = "Rust client for Supabase"
license = "MIT"
repository = "https://github.com/jun784/supabase-rust"
documentation = "https://docs.rs/supabase-rust"
keywords = ["supabase", "postgres", "database", "api", "client"]
categories = ["database", "api-bindings", "web-programming"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "multipart"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
url = "2.3"
base64 = "0.21"
async-trait = "0.1"
jsonwebtoken = "9.1"
supabase-rust-auth = { version = "0.1.0" }
supabase-rust-postgrest = { version = "0.1.0" }
# まだ公開されていないクレートはコメントアウト
# supabase-rust-storage = { path = "crates/storage" }
# supabase-rust-realtime = { path = "crates/realtime" }
# supabase-rust-functions = { path = "crates/functions" }

[workspace]
members = [
    ".",
    "examples",
    "crates/auth",
    "crates/postgrest",
    "crates/storage",
    "crates/realtime",
    "crates/functions"
]

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.0"
wiremock = "0.5"